<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you for your orderYour order has _f1f997</name>
   <tag></tag>
   <elementGuidId>16b3bc66-73b4-4149-989a-8b51c21717d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout_complete_container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkout_complete_container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83146ee1-16b4-43db-acea-d2e1cb98d3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout_complete_container</value>
      <webElementGuid>286bad67-d8bd-4ab7-bbf9-19a4c9589cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout_complete_container</value>
      <webElementGuid>e4077268-59a0-4102-b53c-03410e99eaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>checkout-complete-container</value>
      <webElementGuid>5029ea18-8ab5-4ba4-a515-cf5f3f1e7ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home</value>
      <webElementGuid>7120ad21-d23b-4772-b6e9-8ddb16fc6e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout_complete_container&quot;)</value>
      <webElementGuid>aea4ba0a-3cd6-4a2e-bd23-fb87b2b3340e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='checkout_complete_container']</value>
      <webElementGuid>42dc4e22-a576-48e7-9da7-82f9cee1cc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contents_wrapper']/div[2]</value>
      <webElementGuid>cbdd5c91-62f6-446a-af8a-c2c1d7697b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout: Complete!'])[1]/following::div[1]</value>
      <webElementGuid>90f49955-9475-4e08-a898-4bbc6f607a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swag Labs'])[2]/following::div[3]</value>
      <webElementGuid>992dade9-b462-466a-8a1b-27087831365a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>6438f945-cf95-4b45-b079-052c093e987a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'checkout_complete_container' and (text() = 'Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home' or . = 'Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home')]</value>
      <webElementGuid>3840b2c3-c10d-4d28-a53b-bfd80c1dbf10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
